/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) nlp_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[11] = {4, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3};
static const casadi_int casadi_s4[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};

/* nlp:(x[4],p[])->(f,g) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=7.0710678118654757e-001;
  a1=-1.5046920000000000e+003;
  a2=1.1110000000000000e+000;
  a3=9.8819999999999997e+000;
  a4=arg[0]? arg[0][0] : 0;
  a5=(a3*a4);
  a6=2.9490000000000000e-001;
  a7=(a3*a4);
  a7=atan(a7);
  a3=(a3-a7);
  a6=(a6*a3);
  a5=(a5-a6);
  a5=atan(a5);
  a2=(a2*a5);
  a2=sin(a2);
  a1=(a1*a2);
  a2=(a0*a1);
  a5=7.0710678118654746e-001;
  a6=1.3753319999999999e+003;
  a3=1.3300000000000001e+000;
  a7=1.4779999999999999e+001;
  a8=(a7*a4);
  a9=3.6230000000000001e-001;
  a10=(a7*a4);
  a10=atan(a10);
  a10=(a7-a10);
  a10=(a9*a10);
  a8=(a8-a10);
  a8=atan(a8);
  a8=(a3*a8);
  a8=sin(a8);
  a8=(a6*a8);
  a8=(a5*a8);
  a2=(a2-a8);
  a8=(a0*a1);
  a10=arg[0]? arg[0][1] : 0;
  a11=(a7*a10);
  a12=(a7*a10);
  a12=atan(a12);
  a12=(a7-a12);
  a12=(a9*a12);
  a11=(a11-a12);
  a11=atan(a11);
  a11=(a3*a11);
  a11=sin(a11);
  a11=(a6*a11);
  a11=(a5*a11);
  a8=(a8-a11);
  a2=(a2+a8);
  a8=(a0*a1);
  a11=arg[0]? arg[0][2] : 0;
  a12=(a7*a11);
  a13=(a7*a11);
  a13=atan(a13);
  a13=(a7-a13);
  a13=(a9*a13);
  a12=(a12-a13);
  a12=atan(a12);
  a12=(a3*a12);
  a12=sin(a12);
  a12=(a6*a12);
  a12=(a5*a12);
  a8=(a8-a12);
  a2=(a2+a8);
  a0=(a0*a1);
  a1=arg[0]? arg[0][3] : 0;
  a8=(a7*a1);
  a12=(a7*a1);
  a12=atan(a12);
  a7=(a7-a12);
  a9=(a9*a7);
  a8=(a8-a9);
  a8=atan(a8);
  a3=(a3*a8);
  a3=sin(a3);
  a6=(a6*a3);
  a5=(a5*a6);
  a0=(a0-a5);
  a2=(a2+a0);
  if (res[0]!=0) res[0][0]=a2;
  a4=(a4+a10);
  a4=(a4+a11);
  a4=(a4+a1);
  if (res[1]!=0) res[1][0]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real nlp_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_name_out(casadi_int i){
  switch (i) {
    case 0: return "f";
    case 1: return "g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* nlp_f:(x[4],p[])->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=7.0710678118654757e-001;
  a1=-1.5046920000000000e+003;
  a2=1.1110000000000000e+000;
  a3=9.8819999999999997e+000;
  a4=arg[0]? arg[0][0] : 0;
  a5=(a3*a4);
  a6=2.9490000000000000e-001;
  a7=(a3*a4);
  a7=atan(a7);
  a3=(a3-a7);
  a6=(a6*a3);
  a5=(a5-a6);
  a5=atan(a5);
  a2=(a2*a5);
  a2=sin(a2);
  a1=(a1*a2);
  a2=(a0*a1);
  a5=7.0710678118654746e-001;
  a6=1.3753319999999999e+003;
  a3=1.3300000000000001e+000;
  a7=1.4779999999999999e+001;
  a8=(a7*a4);
  a9=3.6230000000000001e-001;
  a4=(a7*a4);
  a4=atan(a4);
  a4=(a7-a4);
  a4=(a9*a4);
  a8=(a8-a4);
  a8=atan(a8);
  a8=(a3*a8);
  a8=sin(a8);
  a8=(a6*a8);
  a8=(a5*a8);
  a2=(a2-a8);
  a8=(a0*a1);
  a4=arg[0]? arg[0][1] : 0;
  a10=(a7*a4);
  a4=(a7*a4);
  a4=atan(a4);
  a4=(a7-a4);
  a4=(a9*a4);
  a10=(a10-a4);
  a10=atan(a10);
  a10=(a3*a10);
  a10=sin(a10);
  a10=(a6*a10);
  a10=(a5*a10);
  a8=(a8-a10);
  a2=(a2+a8);
  a8=(a0*a1);
  a10=arg[0]? arg[0][2] : 0;
  a4=(a7*a10);
  a10=(a7*a10);
  a10=atan(a10);
  a10=(a7-a10);
  a10=(a9*a10);
  a4=(a4-a10);
  a4=atan(a4);
  a4=(a3*a4);
  a4=sin(a4);
  a4=(a6*a4);
  a4=(a5*a4);
  a8=(a8-a4);
  a2=(a2+a8);
  a0=(a0*a1);
  a1=arg[0]? arg[0][3] : 0;
  a8=(a7*a1);
  a1=(a7*a1);
  a1=atan(a1);
  a7=(a7-a1);
  a9=(a9*a7);
  a8=(a8-a9);
  a8=atan(a8);
  a3=(a3*a8);
  a3=sin(a3);
  a6=(a6*a3);
  a5=(a5*a6);
  a0=(a0-a5);
  a2=(a2+a0);
  if (res[0]!=0) res[0][0]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_f_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_f_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_f_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_f_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_f_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_f_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_f_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_f_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real nlp_f_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_f_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_f_name_out(casadi_int i){
  switch (i) {
    case 0: return "f";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* nlp_g:(x[4],p[])->(g) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[0]? arg[0][0] : 0;
  a1=arg[0]? arg[0][1] : 0;
  a0=(a0+a1);
  a1=arg[0]? arg[0][2] : 0;
  a0=(a0+a1);
  a1=arg[0]? arg[0][3] : 0;
  a0=(a0+a1);
  if (res[0]!=0) res[0][0]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_g(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_g_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_g_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_g_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_g_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_g_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_g_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_g_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_g_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_g_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real nlp_g_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_g_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_g_name_out(casadi_int i){
  switch (i) {
    case 0: return "g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_g_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_g_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_g_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* nlp_grad:(x[4],p[],lam_f,lam_g)->(f,g,grad_gamma_x[4],grad_gamma_p[]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a4, a5, a6, a7, a8, a9;
  a0=7.0710678118654757e-001;
  a1=-1.5046920000000000e+003;
  a2=1.1110000000000000e+000;
  a3=9.8819999999999997e+000;
  a4=arg[0]? arg[0][0] : 0;
  a5=(a3*a4);
  a6=2.9490000000000000e-001;
  a7=(a3*a4);
  a8=atan(a7);
  a8=(a3-a8);
  a8=(a6*a8);
  a5=(a5-a8);
  a8=atan(a5);
  a8=(a2*a8);
  a9=sin(a8);
  a9=(a1*a9);
  a10=(a0*a9);
  a11=7.0710678118654746e-001;
  a12=1.3753319999999999e+003;
  a13=1.3300000000000001e+000;
  a14=1.4779999999999999e+001;
  a15=(a14*a4);
  a16=3.6230000000000001e-001;
  a17=(a14*a4);
  a18=atan(a17);
  a18=(a14-a18);
  a18=(a16*a18);
  a15=(a15-a18);
  a18=atan(a15);
  a18=(a13*a18);
  a19=sin(a18);
  a19=(a12*a19);
  a19=(a11*a19);
  a10=(a10-a19);
  a19=(a0*a9);
  a20=arg[0]? arg[0][1] : 0;
  a21=(a14*a20);
  a22=(a14*a20);
  a23=atan(a22);
  a23=(a14-a23);
  a23=(a16*a23);
  a21=(a21-a23);
  a23=atan(a21);
  a23=(a13*a23);
  a24=sin(a23);
  a24=(a12*a24);
  a24=(a11*a24);
  a19=(a19-a24);
  a10=(a10+a19);
  a19=(a0*a9);
  a24=arg[0]? arg[0][2] : 0;
  a25=(a14*a24);
  a26=(a14*a24);
  a27=atan(a26);
  a27=(a14-a27);
  a27=(a16*a27);
  a25=(a25-a27);
  a27=atan(a25);
  a27=(a13*a27);
  a28=sin(a27);
  a28=(a12*a28);
  a28=(a11*a28);
  a19=(a19-a28);
  a10=(a10+a19);
  a9=(a0*a9);
  a19=arg[0]? arg[0][3] : 0;
  a28=(a14*a19);
  a29=(a14*a19);
  a30=atan(a29);
  a30=(a14-a30);
  a30=(a16*a30);
  a28=(a28-a30);
  a30=atan(a28);
  a30=(a13*a30);
  a31=sin(a30);
  a31=(a12*a31);
  a31=(a11*a31);
  a9=(a9-a31);
  a10=(a10+a9);
  if (res[0]!=0) res[0][0]=a10;
  a4=(a4+a20);
  a4=(a4+a24);
  a4=(a4+a19);
  if (res[1]!=0) res[1][0]=a4;
  a4=arg[3]? arg[3][0] : 0;
  a18=cos(a18);
  a19=arg[2]? arg[2][0] : 0;
  a24=(a11*a19);
  a24=(a12*a24);
  a18=(a18*a24);
  a18=(a13*a18);
  a24=1.;
  a15=casadi_sq(a15);
  a15=(a24+a15);
  a18=(a18/a15);
  a15=(a16*a18);
  a17=casadi_sq(a17);
  a17=(a24+a17);
  a15=(a15/a17);
  a15=(a14*a15);
  a15=(a4-a15);
  a18=(a14*a18);
  a15=(a15-a18);
  a8=cos(a8);
  a18=(a0*a19);
  a17=(a0*a19);
  a18=(a18+a17);
  a17=(a0*a19);
  a18=(a18+a17);
  a0=(a0*a19);
  a18=(a18+a0);
  a1=(a1*a18);
  a8=(a8*a1);
  a2=(a2*a8);
  a5=casadi_sq(a5);
  a5=(a24+a5);
  a2=(a2/a5);
  a6=(a6*a2);
  a7=casadi_sq(a7);
  a7=(a24+a7);
  a6=(a6/a7);
  a6=(a3*a6);
  a15=(a15+a6);
  a3=(a3*a2);
  a15=(a15+a3);
  if (res[2]!=0) res[2][0]=a15;
  a23=cos(a23);
  a15=(a11*a19);
  a15=(a12*a15);
  a23=(a23*a15);
  a23=(a13*a23);
  a21=casadi_sq(a21);
  a21=(a24+a21);
  a23=(a23/a21);
  a21=(a16*a23);
  a22=casadi_sq(a22);
  a22=(a24+a22);
  a21=(a21/a22);
  a21=(a14*a21);
  a21=(a4-a21);
  a23=(a14*a23);
  a21=(a21-a23);
  if (res[2]!=0) res[2][1]=a21;
  a27=cos(a27);
  a21=(a11*a19);
  a21=(a12*a21);
  a27=(a27*a21);
  a27=(a13*a27);
  a25=casadi_sq(a25);
  a25=(a24+a25);
  a27=(a27/a25);
  a25=(a16*a27);
  a26=casadi_sq(a26);
  a26=(a24+a26);
  a25=(a25/a26);
  a25=(a14*a25);
  a25=(a4-a25);
  a27=(a14*a27);
  a25=(a25-a27);
  if (res[2]!=0) res[2][2]=a25;
  a30=cos(a30);
  a11=(a11*a19);
  a12=(a12*a11);
  a30=(a30*a12);
  a13=(a13*a30);
  a28=casadi_sq(a28);
  a28=(a24+a28);
  a13=(a13/a28);
  a16=(a16*a13);
  a29=casadi_sq(a29);
  a24=(a24+a29);
  a16=(a16/a24);
  a16=(a14*a16);
  a4=(a4-a16);
  a14=(a14*a13);
  a4=(a4-a14);
  if (res[2]!=0) res[2][3]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_grad(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_grad_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_grad_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_grad_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_grad_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_grad_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_grad_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_grad_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_grad_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int nlp_grad_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real nlp_grad_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_grad_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    case 2: return "lam_f";
    case 3: return "lam_g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_grad_name_out(casadi_int i){
  switch (i) {
    case 0: return "f";
    case 1: return "g";
    case 2: return "grad_gamma_x";
    case 3: return "grad_gamma_p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_grad_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_grad_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s2;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_grad_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* nlp_grad_f:(x[4],p[])->(f,grad_f_x[4]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a3, a4, a5, a6, a7, a8, a9;
  a0=7.0710678118654757e-001;
  a1=-1.5046920000000000e+003;
  a2=1.1110000000000000e+000;
  a3=9.8819999999999997e+000;
  a4=arg[0]? arg[0][0] : 0;
  a5=(a3*a4);
  a6=2.9490000000000000e-001;
  a7=(a3*a4);
  a8=atan(a7);
  a8=(a3-a8);
  a8=(a6*a8);
  a5=(a5-a8);
  a8=atan(a5);
  a8=(a2*a8);
  a9=sin(a8);
  a1=(a1*a9);
  a9=(a0*a1);
  a10=7.0710678118654746e-001;
  a11=1.3753319999999999e+003;
  a12=1.3300000000000001e+000;
  a13=1.4779999999999999e+001;
  a14=(a13*a4);
  a15=3.6230000000000001e-001;
  a4=(a13*a4);
  a16=atan(a4);
  a16=(a13-a16);
  a16=(a15*a16);
  a14=(a14-a16);
  a16=atan(a14);
  a16=(a12*a16);
  a17=sin(a16);
  a17=(a11*a17);
  a17=(a10*a17);
  a9=(a9-a17);
  a17=(a0*a1);
  a18=arg[0]? arg[0][1] : 0;
  a19=(a13*a18);
  a18=(a13*a18);
  a20=atan(a18);
  a20=(a13-a20);
  a20=(a15*a20);
  a19=(a19-a20);
  a20=atan(a19);
  a20=(a12*a20);
  a21=sin(a20);
  a21=(a11*a21);
  a21=(a10*a21);
  a17=(a17-a21);
  a9=(a9+a17);
  a17=(a0*a1);
  a21=arg[0]? arg[0][2] : 0;
  a22=(a13*a21);
  a21=(a13*a21);
  a23=atan(a21);
  a23=(a13-a23);
  a23=(a15*a23);
  a22=(a22-a23);
  a23=atan(a22);
  a23=(a12*a23);
  a24=sin(a23);
  a24=(a11*a24);
  a24=(a10*a24);
  a17=(a17-a24);
  a9=(a9+a17);
  a0=(a0*a1);
  a1=arg[0]? arg[0][3] : 0;
  a17=(a13*a1);
  a1=(a13*a1);
  a24=atan(a1);
  a24=(a13-a24);
  a24=(a15*a24);
  a17=(a17-a24);
  a24=atan(a17);
  a24=(a12*a24);
  a25=sin(a24);
  a11=(a11*a25);
  a10=(a10*a11);
  a0=(a0-a10);
  a9=(a9+a0);
  if (res[0]!=0) res[0][0]=a9;
  a9=-9.7250658358285659e+002;
  a16=cos(a16);
  a16=(a9*a16);
  a16=(a12*a16);
  a0=1.;
  a14=casadi_sq(a14);
  a14=(a0+a14);
  a16=(a16/a14);
  a14=(a15*a16);
  a4=casadi_sq(a4);
  a4=(a0+a4);
  a14=(a14/a4);
  a14=(a13*a14);
  a16=(a13*a16);
  a14=(a14+a16);
  a16=-4.2559116671885949e+003;
  a8=cos(a8);
  a16=(a16*a8);
  a2=(a2*a16);
  a5=casadi_sq(a5);
  a5=(a0+a5);
  a2=(a2/a5);
  a6=(a6*a2);
  a7=casadi_sq(a7);
  a7=(a0+a7);
  a6=(a6/a7);
  a6=(a3*a6);
  a14=(a14+a6);
  a3=(a3*a2);
  a14=(a14+a3);
  if (res[1]!=0) res[1][0]=a14;
  a20=cos(a20);
  a20=(a9*a20);
  a20=(a12*a20);
  a19=casadi_sq(a19);
  a19=(a0+a19);
  a20=(a20/a19);
  a19=(a15*a20);
  a18=casadi_sq(a18);
  a18=(a0+a18);
  a19=(a19/a18);
  a19=(a13*a19);
  a20=(a13*a20);
  a19=(a19+a20);
  if (res[1]!=0) res[1][1]=a19;
  a23=cos(a23);
  a23=(a9*a23);
  a23=(a12*a23);
  a22=casadi_sq(a22);
  a22=(a0+a22);
  a23=(a23/a22);
  a22=(a15*a23);
  a21=casadi_sq(a21);
  a21=(a0+a21);
  a22=(a22/a21);
  a22=(a13*a22);
  a23=(a13*a23);
  a22=(a22+a23);
  if (res[1]!=0) res[1][2]=a22;
  a24=cos(a24);
  a9=(a9*a24);
  a12=(a12*a9);
  a17=casadi_sq(a17);
  a17=(a0+a17);
  a12=(a12/a17);
  a15=(a15*a12);
  a1=casadi_sq(a1);
  a0=(a0+a1);
  a15=(a15/a0);
  a15=(a13*a15);
  a13=(a13*a12);
  a15=(a15+a13);
  if (res[1]!=0) res[1][3]=a15;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_grad_f(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_grad_f_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_grad_f_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_grad_f_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_grad_f_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_grad_f_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_grad_f_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_grad_f_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_grad_f_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_grad_f_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real nlp_grad_f_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_grad_f_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_grad_f_name_out(casadi_int i){
  switch (i) {
    case 0: return "f";
    case 1: return "grad_f_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_grad_f_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_grad_f_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_grad_f_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* nlp_hess_l:(x[4],p[],lam_f,lam_g)->(hess_gamma_x_x[4x4,4nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=1.4779999999999999e+001;
  a1=3.6230000000000001e-001;
  a2=1.3300000000000001e+000;
  a3=1.3753319999999999e+003;
  a4=7.0710678118654746e-001;
  a5=arg[2]? arg[2][0] : 0;
  a6=(a4*a5);
  a6=(a3*a6);
  a7=arg[0]? arg[0][0] : 0;
  a8=(a0*a7);
  a9=(a0*a7);
  a10=atan(a9);
  a10=(a0-a10);
  a10=(a1*a10);
  a8=(a8-a10);
  a10=atan(a8);
  a10=(a2*a10);
  a11=sin(a10);
  a12=1.;
  a13=casadi_sq(a9);
  a13=(a12+a13);
  a13=(a0/a13);
  a13=(a1*a13);
  a13=(a0+a13);
  a14=casadi_sq(a8);
  a14=(a12+a14);
  a14=(a13/a14);
  a14=(a2*a14);
  a11=(a11*a14);
  a11=(a6*a11);
  a11=(a2*a11);
  a14=casadi_sq(a8);
  a14=(a12+a14);
  a11=(a11/a14);
  a10=cos(a10);
  a10=(a10*a6);
  a10=(a2*a10);
  a10=(a10/a14);
  a14=(a10/a14);
  a8=(a8+a8);
  a8=(a8*a13);
  a14=(a14*a8);
  a11=(a11+a14);
  a14=(a1*a11);
  a8=casadi_sq(a9);
  a8=(a12+a8);
  a14=(a14/a8);
  a10=(a1*a10);
  a10=(a10/a8);
  a10=(a10/a8);
  a9=(a9+a9);
  a9=(a0*a9);
  a10=(a10*a9);
  a14=(a14+a10);
  a14=(a0*a14);
  a11=(a0*a11);
  a14=(a14+a11);
  a11=9.8819999999999997e+000;
  a10=2.9490000000000000e-001;
  a9=1.1110000000000000e+000;
  a8=-1.5046920000000000e+003;
  a13=7.0710678118654757e-001;
  a6=(a13*a5);
  a15=(a13*a5);
  a6=(a6+a15);
  a15=(a13*a5);
  a6=(a6+a15);
  a13=(a13*a5);
  a6=(a6+a13);
  a8=(a8*a6);
  a6=(a11*a7);
  a7=(a11*a7);
  a13=atan(a7);
  a13=(a11-a13);
  a13=(a10*a13);
  a6=(a6-a13);
  a13=atan(a6);
  a13=(a9*a13);
  a15=sin(a13);
  a16=casadi_sq(a7);
  a16=(a12+a16);
  a16=(a11/a16);
  a16=(a10*a16);
  a16=(a11+a16);
  a17=casadi_sq(a6);
  a17=(a12+a17);
  a17=(a16/a17);
  a17=(a9*a17);
  a15=(a15*a17);
  a15=(a8*a15);
  a15=(a9*a15);
  a17=casadi_sq(a6);
  a17=(a12+a17);
  a15=(a15/a17);
  a13=cos(a13);
  a13=(a13*a8);
  a9=(a9*a13);
  a9=(a9/a17);
  a17=(a9/a17);
  a6=(a6+a6);
  a6=(a6*a16);
  a17=(a17*a6);
  a15=(a15+a17);
  a17=(a10*a15);
  a6=casadi_sq(a7);
  a6=(a12+a6);
  a17=(a17/a6);
  a10=(a10*a9);
  a10=(a10/a6);
  a10=(a10/a6);
  a7=(a7+a7);
  a7=(a11*a7);
  a10=(a10*a7);
  a17=(a17+a10);
  a17=(a11*a17);
  a14=(a14-a17);
  a11=(a11*a15);
  a14=(a14-a11);
  if (res[0]!=0) res[0][0]=a14;
  a14=(a4*a5);
  a14=(a3*a14);
  a11=arg[0]? arg[0][1] : 0;
  a15=(a0*a11);
  a11=(a0*a11);
  a17=atan(a11);
  a17=(a0-a17);
  a17=(a1*a17);
  a15=(a15-a17);
  a17=atan(a15);
  a17=(a2*a17);
  a10=sin(a17);
  a7=casadi_sq(a11);
  a7=(a12+a7);
  a7=(a0/a7);
  a7=(a1*a7);
  a7=(a0+a7);
  a6=casadi_sq(a15);
  a6=(a12+a6);
  a6=(a7/a6);
  a6=(a2*a6);
  a10=(a10*a6);
  a10=(a14*a10);
  a10=(a2*a10);
  a6=casadi_sq(a15);
  a6=(a12+a6);
  a10=(a10/a6);
  a17=cos(a17);
  a17=(a17*a14);
  a17=(a2*a17);
  a17=(a17/a6);
  a6=(a17/a6);
  a15=(a15+a15);
  a15=(a15*a7);
  a6=(a6*a15);
  a10=(a10+a6);
  a6=(a1*a10);
  a15=casadi_sq(a11);
  a15=(a12+a15);
  a6=(a6/a15);
  a17=(a1*a17);
  a17=(a17/a15);
  a17=(a17/a15);
  a11=(a11+a11);
  a11=(a0*a11);
  a17=(a17*a11);
  a6=(a6+a17);
  a6=(a0*a6);
  a10=(a0*a10);
  a6=(a6+a10);
  if (res[0]!=0) res[0][1]=a6;
  a6=(a4*a5);
  a6=(a3*a6);
  a10=arg[0]? arg[0][2] : 0;
  a17=(a0*a10);
  a10=(a0*a10);
  a11=atan(a10);
  a11=(a0-a11);
  a11=(a1*a11);
  a17=(a17-a11);
  a11=atan(a17);
  a11=(a2*a11);
  a15=sin(a11);
  a7=casadi_sq(a10);
  a7=(a12+a7);
  a7=(a0/a7);
  a7=(a1*a7);
  a7=(a0+a7);
  a14=casadi_sq(a17);
  a14=(a12+a14);
  a14=(a7/a14);
  a14=(a2*a14);
  a15=(a15*a14);
  a15=(a6*a15);
  a15=(a2*a15);
  a14=casadi_sq(a17);
  a14=(a12+a14);
  a15=(a15/a14);
  a11=cos(a11);
  a11=(a11*a6);
  a11=(a2*a11);
  a11=(a11/a14);
  a14=(a11/a14);
  a17=(a17+a17);
  a17=(a17*a7);
  a14=(a14*a17);
  a15=(a15+a14);
  a14=(a1*a15);
  a17=casadi_sq(a10);
  a17=(a12+a17);
  a14=(a14/a17);
  a11=(a1*a11);
  a11=(a11/a17);
  a11=(a11/a17);
  a10=(a10+a10);
  a10=(a0*a10);
  a11=(a11*a10);
  a14=(a14+a11);
  a14=(a0*a14);
  a15=(a0*a15);
  a14=(a14+a15);
  if (res[0]!=0) res[0][2]=a14;
  a4=(a4*a5);
  a3=(a3*a4);
  a4=arg[0]? arg[0][3] : 0;
  a5=(a0*a4);
  a4=(a0*a4);
  a14=atan(a4);
  a14=(a0-a14);
  a14=(a1*a14);
  a5=(a5-a14);
  a14=atan(a5);
  a14=(a2*a14);
  a15=sin(a14);
  a11=casadi_sq(a4);
  a11=(a12+a11);
  a11=(a0/a11);
  a11=(a1*a11);
  a11=(a0+a11);
  a10=casadi_sq(a5);
  a10=(a12+a10);
  a10=(a11/a10);
  a10=(a2*a10);
  a15=(a15*a10);
  a15=(a3*a15);
  a15=(a2*a15);
  a10=casadi_sq(a5);
  a10=(a12+a10);
  a15=(a15/a10);
  a14=cos(a14);
  a14=(a14*a3);
  a2=(a2*a14);
  a2=(a2/a10);
  a10=(a2/a10);
  a5=(a5+a5);
  a5=(a5*a11);
  a10=(a10*a5);
  a15=(a15+a10);
  a10=(a1*a15);
  a5=casadi_sq(a4);
  a12=(a12+a5);
  a10=(a10/a12);
  a1=(a1*a2);
  a1=(a1/a12);
  a1=(a1/a12);
  a4=(a4+a4);
  a4=(a0*a4);
  a1=(a1*a4);
  a10=(a10+a1);
  a10=(a0*a10);
  a0=(a0*a15);
  a10=(a10+a0);
  if (res[0]!=0) res[0][3]=a10;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_hess_l(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_hess_l_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_hess_l_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_hess_l_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_hess_l_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_hess_l_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_hess_l_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_hess_l_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_hess_l_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int nlp_hess_l_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real nlp_hess_l_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_hess_l_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    case 2: return "lam_f";
    case 3: return "lam_g";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_hess_l_name_out(casadi_int i){
  switch (i) {
    case 0: return "hess_gamma_x_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_hess_l_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_hess_l_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_hess_l_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* nlp_jac_g:(x[4],p[])->(g,jac_g_x[1x4]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[0]? arg[0][0] : 0;
  a1=arg[0]? arg[0][1] : 0;
  a0=(a0+a1);
  a1=arg[0]? arg[0][2] : 0;
  a0=(a0+a1);
  a1=arg[0]? arg[0][3] : 0;
  a0=(a0+a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=1.;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  if (res[1]!=0) res[1][2]=a0;
  if (res[1]!=0) res[1][3]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_jac_g(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int nlp_jac_g_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int nlp_jac_g_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_jac_g_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int nlp_jac_g_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void nlp_jac_g_release(int mem) {
}

CASADI_SYMBOL_EXPORT void nlp_jac_g_incref(void) {
}

CASADI_SYMBOL_EXPORT void nlp_jac_g_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int nlp_jac_g_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int nlp_jac_g_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real nlp_jac_g_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_jac_g_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* nlp_jac_g_name_out(casadi_int i){
  switch (i) {
    case 0: return "g";
    case 1: return "jac_g_x";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_jac_g_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* nlp_jac_g_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int nlp_jac_g_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
